### PR TITLE
Refactor recursive-aggregation feature

### PR DESCRIPTION
**Pull request by danielhuppmann**
# Please confirm that this PR has done the following:

- [ ] Tests Added
- [ ] Documentation Added
- [ ] Name of contributors Added to AUTHORS.rst
- [ ] Description in RELEASE_NOTES.md Added

## Adding to RELEASE_NOTES.md (remove section after adding to RELEASE_NOTES.md)

Please add a single line in the release notes similar to the following:

```
- (#XX)[http://link-to-pr.com] Added feature which does something
```

# Description of PR

This PR refactors the implementation of the recursive-aggregation feature avoiding calling `data`.

### CODE REVIEW

**Comment by danielhuppmann** [comment]
@tburandt, as far as I know, you are the user that heavily uses the recursive-aggregation feature in a real-word application,. Could you please test this branch whether it yields the same result as the previous implementation, and maybe also report on the speed improvement?

**Comment by danielhuppmann** [comment]
fyi @coroa

**Comment by tburandt** [comment]
@danielhuppmann the recursive aggregation works like a charm even with large(er) data. It _seems_ also faster than before, but I forgot to measure the time (unfortunately)

**Comment by danielhuppmann** [comment]
thanks @tburandt for taking a look!

**Pull request merged**
