### PR TITLE
Add an `info()` function and use in `print(df)`

### PR DESCRIPTION
**Pull request by danielhuppmann**
# Please confirm that this PR has done the following:

- [x] Tests Added
- [x] Documentation Added

# Description of PR

This PR adds an `info()` function similar to the pandas equivalent ([read the docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html)) and when calling `print()` on an xarray object, which is the also used in `print(df)` (via `__repr__`).

The output in the first-steps tutorial is:
```
<class 'pyam.core.IamDataFrame'>
Index dimensions:
 * model    : AIM/CGE 2.1, GENeSYS-MOD 1.0, ... WITCH-GLOBIOM 4.4 (8)
 * scenario : 1.0, CD-LINKS_INDCi, CD-LINKS_NPi, ... Faster Transition Scenario (8)
 * region   : R5ASIA, R5LAM, R5MAF, R5OECD90+EU, R5REF, R5ROWO, World (7)
 * variable : ... (6)
 * unit     : EJ/yr, Mt CO2/yr, °C (3)
 * year     : 2010, 2020, 2030, 2040, 2050, 2060, 2070, 2080, ... 2100 (10)
Meta indicators:
   exclude (bool) False (1)
```

### CODE REVIEW

**Comment by danielhuppmann** [comment]
@gidden @znicholls @Rlamboll - any thoughts on this `IamDataFrame.info()` function?

**Comment by Rlamboll** [comment]
I get that this could be useful, but it's not what I normally expect when printing a df (head+tail+length info, in keeping with what pandas returns for a print command). The most important thing missing is some indication of the size of the the object, e.g. total number of rows of data, number of scenarios etc. rather than just "more than 5". For first time users it might be helpful to name the datatype and state that you're printing summary statistics, not properties of the system (otherwise it's confusing that you need ".scenarios()" not ".scenario" to access the list of scenarios).

**Comment by danielhuppmann** [comment]
Thanks @Rlamboll for your comments! In my view, an `IamDataFrame` is a lot more than just a `pandas.DataFrame`, so it makes sense to follow the route of `Dataframe.info()` or an xarray representation.

I added a type and a memory usage info to the overview. I played around with including the numbers of each dimension, but this becomes too dense (I think). Note that there is already `df.head()` and `df.tail()` for behavior more like printing a `pandas.DataFrame` and `len(df)` to get the number of data points.

Also, I fully agree that `df.scenario` is a more intuitive API than `df.scenarios()` so let's add that option (or deprecate the other one in the future) in a next PR.

**Comment by Rlamboll** [comment]
Listing the type indeed helps to contexualise it and makes it look better. 

I don't mind behaviour more like xarray, but note that both `print(<xarray>)` and `<xarray>` as the last line of a juptyer cell (which are different) lists each dimension size, as well as some example values (which you leave out entirely here). Given its structure, this also determines the total size, not true for our case where data may be incomplete. If it's too dense with five examples and (total: <n>) added, can't you just change it to only list 4 examples and the total for each dimension? xarray presents a variable number of values and goes down to 2 if the names are really long, which I think is the source of your appearance density problem here. Memory usage is not on my list of top 10 things I want to know about a df if you're worried about length.

**Comment by danielhuppmann** [comment]
closing in favor of https://github.com/IAMconsortium/pyam/pull/427

**Pull request closed without merging**
